[build]
cmd = "composer install --no-dev --optimize-autoloader && npm ci && npm run production && php artisan optimize && php artisan config:cache && php artisan route:cache && php artisan view:cache"
